version: "3.8"

services:
  event-receiver:
    image: ghcr.io/dws-1-2026-green/eventreceiver:master
    container_name: event-receiver
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: kafka:9094
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - kafka-net
      - monitoring-net

  delivery-service:
    image: ghcr.io/dws-1-2026-green/delivery-service:develop
    container_name: delivery-service
    restart: unless-stopped
    environment:
      KAFKA_BROKERS: kafka:9094
      KAFKA_TOPIC: deliveries.to_send
      METRICS_ADDR: ":9095"
    ports:
      - "9095:9095"
    depends_on:
      - kafka
    networks:
      - kafka-net
      - monitoring-net

  subscriptions-api:
    image: ghcr.io/dws-1-2026-green/subscriptions-api:main
    container_name: subscriptions-api
    restart: unless-stopped

    environment:
      STORE_BACKEND: cassandra
      CASSANDRA_HOSTS: cassandra
      HTTP_ADDR: 8082
    ports:
      - "8082:8082"
    networks:
      - kafka-net
      - cassandra-net
      - monitoring-net
    depends_on:
      kafka:
        condition: service_started
      cassandra:
        condition: service_healthy

  subscriptions-worker:
    image: ghcr.io/dws-1-2026-green/subscriptions-worker:main
    container_name: subscriptions-worker
    restart: unless-stopped

    environment:
      KAFKA_BROKERS: kafka:9094
      STORE_BACKEND: cassandra
      CASSANDRA_HOSTS: cassandra
      METRICS_ADDR: ":9091"
    ports:
      - "9091:9091"
    networks:
      - kafka-net
      - cassandra-net
      - monitoring-net
    depends_on:
      kafka:
        condition: service_started
      cassandra:
        condition: service_healthy

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Слушаем на двух портах:
      # 9092 - для подключений с хоста
      # 9094 - для подключений внутри Docker-сети
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      # Рекламируем оба адреса:
      # localhost:9092 - для приложений на хосте
      # kafka:9094 - для сервисов внутри Docker (kafka-ui)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9094

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    ports:
      - "8081:8080"
    networks:
      - kafka-net

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "WebhooksCluster"
      CASSANDRA_DC: "dc1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"
    networks:
      - cassandra-net
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  cassandra-init:
    image: cassandra:4.1
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra/20260428192921_init.up.cql:/schema.cql:ro
    command: [ "cqlsh", "cassandra", "-f", "/schema.cql" ]
    restart: "no"
    networks:
      - cassandra-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    depends_on:
      - event-receiver
      - subscriptions-worker
      - delivery-service
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring-net

networks:
  kafka-net:
    driver: bridge
  cassandra-net:
    driver: bridge
  monitoring-net:
    driver: bridge

volumes:
  kafka-data:
  postgres_data:
  prometheus_data:
  grafana_data:
  cassandra_data:
