apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: webhooks
data:
  dashboards.yml: |
    apiVersion: 1

    providers:
      - name: default
        orgId: 1
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /etc/grafana/provisioning/dashboards
          foldersFromFilesStructure: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: webhooks
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-0.prometheus.webhooks.svc.cluster.local:9090
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-0.loki.webhooks.svc.cluster.local:3100
        editable: false
