apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          args:
            - "--kafka.server=kafka-0.kafka.webhooks.svc.cluster.local:9094"
          ports:
            - containerPort: 9308
