apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: webhooks
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-external
  namespace: webhooks
spec:
  type: LoadBalancer
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
