apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhooks-local
  namespace: webhooks
spec:
  ingressClassName: nginx
  rules:
    - host: event-receiver.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-receiver
                port:
                  number: 8080
    - host: subscriptions.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subscriptions-api
                port:
                  number: 8082
    - host: kafka-ui.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 8080
    - host: prometheus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
    - host: grafana.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: loki.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki
                port:
                  number: 3100
    - host: delivery-dashboard.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: delivery-dashboard
                port:
                  number: 9096
