apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: webhooks
data:
  KAFKA_TOPIC: "deliveries.to_send"
  KAFKA_GROUP_ID: "delivery-group"
  METRICS_ADDR: ":9095"
  CONSUMER_WORKERS: "50"
  BACKOFF_BASE_DELAY: "5s"
  BACKOFF_MAX_DELAY: "24h"
  BACKOFF_MAX_ATTEMPTS: "10"
