global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'event-receiver'
    static_configs:
      - targets: ['event-receiver:8080']
    metrics_path: '/metrics'

  - job_name: 'subscriptions-worker'
    static_configs:
      - targets: ['subscriptions-worker:9091']
    metrics_path: '/metrics'

  - job_name: 'subscriptions-api'
    static_configs:
      - targets: ['subscriptions-api:8080']
    metrics_path: '/metrics'

  - job_name: 'delivery-service'
    static_configs:
      - targets: ['delivery-service:9095']
    metrics_path: '/metrics'
    
 
