apiVersion: v1
kind: Service
metadata:
  name: host-webhook-listener
  namespace: webhooks
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 8888
      targetPort: 8888