apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webhooks

resources:
  - namespace.yaml

  - messaging/kafka.yaml
  - messaging/kafka-ui.yaml

  - storage/cassandra.yaml

  - apps/event-receiver.yaml
  - apps/delivery-service.yaml
  - apps/subscriptions-api.yaml
  - apps/subscriptions-worker.yaml

  - observability/prometheus.yaml
  - observability/grafana.yaml
  - observability/loki.yaml
  - observability/alloy.yaml
