apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webhooks

resources:
  - namespace.yaml

  - messaging/kafka.yaml
  - messaging/kafka-ui.yaml

  - storage/cassandra.yaml
  - storage/postgres.yaml

  - apps/event-receiver.yaml
  - apps/delivery-service.yaml
  - apps/subscriptions-api.yaml
  - apps/subscriptions-worker.yaml

  - observability/0-grafana-config.yaml
  - observability/1-alloy.yaml
  - observability/2-loki.yaml
  - observability/3-prometheus.yaml
  - observability/4-grafana.yaml
  - observability/5-delivery-dashboard.yaml
  - observability/6-kafka-exporter.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-subscriptions
    files:
      - subscriptions.json=dashboards/subscriptions.json
  - name: grafana-dashboard-overview
    files:
      - overview.json=dashboards/overview.json
  - name: grafana-dashboard-delivery-service
    files:
      - delivery-service.json=dashboards/delivery-service.json
  - name: grafana-dashboard-event-receiver
    files:
      - event-receiver.json=dashboards/event-receiver.json
