apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-schema
  namespace: webhooks
data:
  init.up.cql: |
    CREATE KEYSPACE IF NOT EXISTS webhooks
    WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': 1}
    AND durable_writes = true;

    -- Lookup by (source, event_type); subscription_id как clustering key
    CREATE TABLE IF NOT EXISTS webhooks.subscriptions (
        source text,
        event_type text,
        subscription_id uuid,
        destination_url text,
        http_method text,
        headers frozen<map<text, text>>,
        enabled boolean,
        created_at timestamp,
        PRIMARY KEY ((source, event_type), subscription_id)
    ) WITH CLUSTERING ORDER BY (subscription_id ASC)
      AND default_time_to_live = 0
      AND gc_grace_seconds = 86400;

    -- Lookup by subscription_id (CRUD)
    CREATE TABLE IF NOT EXISTS webhooks.subscriptions_by_id (
      subscription_id uuid PRIMARY KEY,
      source text,
      event_type text,
      destination_url text,
      http_method text,
      headers frozen<map<text, text>>,
      enabled boolean,
      created_at timestamp
    );
